<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2024-03-19T17:35:14.649169Z</date>
  <millis>1710869714649</millis>
  <nanos>169000</nanos>
  <sequence>0</sequence>
  <logger>LoggingUtility</logger>
  <level>WARNING</level>
  <class>RegStrategy</class>
  <method>validate</method>
  <thread>1</thread>
  <message>Date validation failed for personal number: 301701102384</message>
</record>
<record>
  <date>2024-03-19T17:35:14.662153Z</date>
  <millis>1710869714662</millis>
  <nanos>153000</nanos>
  <sequence>1</sequence>
  <logger>LoggingUtility</logger>
  <level>WARNING</level>
  <class>RegStrategy</class>
  <method>validate</method>
  <thread>1</thread>
  <message>Luhn's algorithm validation failed for personal number: 201701272394</message>
</record>
<record>
  <date>2024-03-19T17:35:14.662918Z</date>
  <millis>1710869714662</millis>
  <nanos>918000</nanos>
  <sequence>2</sequence>
  <logger>LoggingUtility</logger>
  <level>WARNING</level>
  <class>DateValidator</class>
  <method>isDateValid</method>
  <thread>1</thread>
  <message>Exception occured while validating date for personal number: 190302299813</message>
  <param>Invalid date 'February 29' as '1903' is not a leap year</param>
</record>
<record>
  <date>2024-03-19T17:35:14.663511Z</date>
  <millis>1710869714663</millis>
  <nanos>511000</nanos>
  <sequence>3</sequence>
  <logger>LoggingUtility</logger>
  <level>WARNING</level>
  <class>RegStrategy</class>
  <method>validate</method>
  <thread>1</thread>
  <message>Date validation failed for personal number: 190302299813</message>
</record>
</log>
